package com.ra1ph.giphysample.data.source.local;

import com.ra1ph.giphysample.search.domain.GifModel;

import io.objectbox.annotation.Convert;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.converter.PropertyConverter;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import com.ra1ph.giphysample.search.domain.GifModel.Vote;

/**
 * Created by Mikhail Korshunov on 09.08.17.
 */

@Entity
class VoteEntity {
    @Id
    private long id;

    private String giphyId;
    @Convert(converter = VoteConverter.class, dbType = Integer.class)
    private GifModel.Vote vote;

    VoteEntity(String giphyId) {
        this.giphyId = giphyId;
        this.vote = GifModel.Vote.NONE;
    }

    @Generated(1168923361)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public VoteEntity(long id, String giphyId, GifModel.Vote vote) {
        this.id = id;
        this.giphyId = giphyId;
        this.vote = vote;
    }

    @Generated(1287062521)
    public VoteEntity() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getGiphyId() {
        return giphyId;
    }

    public void setGiphyId(String giphyId) {
        this.giphyId = giphyId;
    }

    public GifModel.Vote getVote() {
        return vote;
    }

    public void setVote(GifModel.Vote vote) {
        this.vote = vote;
    }

    public static class VoteConverter implements PropertyConverter<GifModel.Vote, Integer> {
        @Override
        public GifModel.Vote convertToEntityProperty(Integer databaseValue) {
            if (databaseValue == null || databaseValue < 0 || databaseValue >= GifModel.Vote.values().length) { //wrong value in DB
                return GifModel.Vote.NONE;
            }
            return GifModel.Vote.values()[databaseValue];
        }

        @Override
        public Integer convertToDatabaseValue(GifModel.Vote vote) {
            return vote.ordinal();
        }
    }
}
